// Code generated by sqlc. DO NOT EDIT.
// source: connector.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createConnector = `-- name: CreateConnector :one
INSERT INTO connectors (
    evse_id, 
    uid, 
    identifier, 
    standard, 
    format, 
    power_type, 
    voltage, 
    amperage, 
    wattage, 
    tariff_id, 
    terms_and_conditions, 
    publish,
    last_updated)
  VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
  RETURNING id, evse_id, uid, identifier, standard, format, power_type, voltage, amperage, wattage, tariff_id, terms_and_conditions, last_updated, publish
`

type CreateConnectorParams struct {
	EvseID             int64           `db:"evse_id" json:"evseID"`
	Uid                string          `db:"uid" json:"uid"`
	Identifier         sql.NullString  `db:"identifier" json:"identifier"`
	Standard           ConnectorType   `db:"standard" json:"standard"`
	Format             ConnectorFormat `db:"format" json:"format"`
	PowerType          PowerType       `db:"power_type" json:"powerType"`
	Voltage            int32           `db:"voltage" json:"voltage"`
	Amperage           int32           `db:"amperage" json:"amperage"`
	Wattage            int32           `db:"wattage" json:"wattage"`
	TariffID           sql.NullString  `db:"tariff_id" json:"tariffID"`
	TermsAndConditions sql.NullString  `db:"terms_and_conditions" json:"termsAndConditions"`
	Publish            bool            `db:"publish" json:"publish"`
	LastUpdated        time.Time       `db:"last_updated" json:"lastUpdated"`
}

func (q *Queries) CreateConnector(ctx context.Context, arg CreateConnectorParams) (Connector, error) {
	row := q.db.QueryRowContext(ctx, createConnector,
		arg.EvseID,
		arg.Uid,
		arg.Identifier,
		arg.Standard,
		arg.Format,
		arg.PowerType,
		arg.Voltage,
		arg.Amperage,
		arg.Wattage,
		arg.TariffID,
		arg.TermsAndConditions,
		arg.Publish,
		arg.LastUpdated,
	)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.EvseID,
		&i.Uid,
		&i.Identifier,
		&i.Standard,
		&i.Format,
		&i.PowerType,
		&i.Voltage,
		&i.Amperage,
		&i.Wattage,
		&i.TariffID,
		&i.TermsAndConditions,
		&i.LastUpdated,
		&i.Publish,
	)
	return i, err
}

const deleteConnector = `-- name: DeleteConnector :exec
DELETE FROM connectors
  WHERE id = $1
`

func (q *Queries) DeleteConnector(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteConnector, id)
	return err
}

const deleteConnectorByEvse = `-- name: DeleteConnectorByEvse :exec
DELETE FROM connectors
  WHERE evse_id = $1 AND uid = $2
`

type DeleteConnectorByEvseParams struct {
	EvseID int64  `db:"evse_id" json:"evseID"`
	Uid    string `db:"uid" json:"uid"`
}

func (q *Queries) DeleteConnectorByEvse(ctx context.Context, arg DeleteConnectorByEvseParams) error {
	_, err := q.db.ExecContext(ctx, deleteConnectorByEvse, arg.EvseID, arg.Uid)
	return err
}

const deleteConnectors = `-- name: DeleteConnectors :exec
DELETE FROM connectors
  WHERE evse_id = $1
`

func (q *Queries) DeleteConnectors(ctx context.Context, evseID int64) error {
	_, err := q.db.ExecContext(ctx, deleteConnectors, evseID)
	return err
}

const getConnector = `-- name: GetConnector :one
SELECT id, evse_id, uid, identifier, standard, format, power_type, voltage, amperage, wattage, tariff_id, terms_and_conditions, last_updated, publish FROM connectors
  WHERE id = $1
`

func (q *Queries) GetConnector(ctx context.Context, id int64) (Connector, error) {
	row := q.db.QueryRowContext(ctx, getConnector, id)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.EvseID,
		&i.Uid,
		&i.Identifier,
		&i.Standard,
		&i.Format,
		&i.PowerType,
		&i.Voltage,
		&i.Amperage,
		&i.Wattage,
		&i.TariffID,
		&i.TermsAndConditions,
		&i.LastUpdated,
		&i.Publish,
	)
	return i, err
}

const getConnectorByEvse = `-- name: GetConnectorByEvse :one
SELECT id, evse_id, uid, identifier, standard, format, power_type, voltage, amperage, wattage, tariff_id, terms_and_conditions, last_updated, publish FROM connectors
  WHERE evse_id = $1 AND uid = $2
`

type GetConnectorByEvseParams struct {
	EvseID int64  `db:"evse_id" json:"evseID"`
	Uid    string `db:"uid" json:"uid"`
}

func (q *Queries) GetConnectorByEvse(ctx context.Context, arg GetConnectorByEvseParams) (Connector, error) {
	row := q.db.QueryRowContext(ctx, getConnectorByEvse, arg.EvseID, arg.Uid)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.EvseID,
		&i.Uid,
		&i.Identifier,
		&i.Standard,
		&i.Format,
		&i.PowerType,
		&i.Voltage,
		&i.Amperage,
		&i.Wattage,
		&i.TariffID,
		&i.TermsAndConditions,
		&i.LastUpdated,
		&i.Publish,
	)
	return i, err
}

const getConnectorByIdentifier = `-- name: GetConnectorByIdentifier :one
SELECT id, evse_id, uid, identifier, standard, format, power_type, voltage, amperage, wattage, tariff_id, terms_and_conditions, last_updated, publish FROM connectors
  WHERE identifier = $1
`

func (q *Queries) GetConnectorByIdentifier(ctx context.Context, identifier sql.NullString) (Connector, error) {
	row := q.db.QueryRowContext(ctx, getConnectorByIdentifier, identifier)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.EvseID,
		&i.Uid,
		&i.Identifier,
		&i.Standard,
		&i.Format,
		&i.PowerType,
		&i.Voltage,
		&i.Amperage,
		&i.Wattage,
		&i.TariffID,
		&i.TermsAndConditions,
		&i.LastUpdated,
		&i.Publish,
	)
	return i, err
}

const listConnectors = `-- name: ListConnectors :many
SELECT id, evse_id, uid, identifier, standard, format, power_type, voltage, amperage, wattage, tariff_id, terms_and_conditions, last_updated, publish FROM connectors
  WHERE evse_id = $1 AND publish = true
  ORDER BY id
`

func (q *Queries) ListConnectors(ctx context.Context, evseID int64) ([]Connector, error) {
	rows, err := q.db.QueryContext(ctx, listConnectors, evseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Connector
	for rows.Next() {
		var i Connector
		if err := rows.Scan(
			&i.ID,
			&i.EvseID,
			&i.Uid,
			&i.Identifier,
			&i.Standard,
			&i.Format,
			&i.PowerType,
			&i.Voltage,
			&i.Amperage,
			&i.Wattage,
			&i.TariffID,
			&i.TermsAndConditions,
			&i.LastUpdated,
			&i.Publish,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConnector = `-- name: UpdateConnector :one
UPDATE connectors SET (
    identifier,
    standard, 
    format, 
    power_type, 
    voltage, 
    amperage, 
    wattage, 
    tariff_id, 
    terms_and_conditions, 
    publish,
    last_updated
  ) = ($2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
  WHERE id = $1
  RETURNING id, evse_id, uid, identifier, standard, format, power_type, voltage, amperage, wattage, tariff_id, terms_and_conditions, last_updated, publish
`

type UpdateConnectorParams struct {
	ID                 int64           `db:"id" json:"id"`
	Identifier         sql.NullString  `db:"identifier" json:"identifier"`
	Standard           ConnectorType   `db:"standard" json:"standard"`
	Format             ConnectorFormat `db:"format" json:"format"`
	PowerType          PowerType       `db:"power_type" json:"powerType"`
	Voltage            int32           `db:"voltage" json:"voltage"`
	Amperage           int32           `db:"amperage" json:"amperage"`
	Wattage            int32           `db:"wattage" json:"wattage"`
	TariffID           sql.NullString  `db:"tariff_id" json:"tariffID"`
	TermsAndConditions sql.NullString  `db:"terms_and_conditions" json:"termsAndConditions"`
	Publish            bool            `db:"publish" json:"publish"`
	LastUpdated        time.Time       `db:"last_updated" json:"lastUpdated"`
}

func (q *Queries) UpdateConnector(ctx context.Context, arg UpdateConnectorParams) (Connector, error) {
	row := q.db.QueryRowContext(ctx, updateConnector,
		arg.ID,
		arg.Identifier,
		arg.Standard,
		arg.Format,
		arg.PowerType,
		arg.Voltage,
		arg.Amperage,
		arg.Wattage,
		arg.TariffID,
		arg.TermsAndConditions,
		arg.Publish,
		arg.LastUpdated,
	)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.EvseID,
		&i.Uid,
		&i.Identifier,
		&i.Standard,
		&i.Format,
		&i.PowerType,
		&i.Voltage,
		&i.Amperage,
		&i.Wattage,
		&i.TariffID,
		&i.TermsAndConditions,
		&i.LastUpdated,
		&i.Publish,
	)
	return i, err
}

const updateConnectorByEvse = `-- name: UpdateConnectorByEvse :one
UPDATE connectors SET (
    identifier,
    standard, 
    format, 
    power_type, 
    voltage, 
    amperage, 
    wattage, 
    tariff_id, 
    terms_and_conditions, 
    publish,
    last_updated
  ) = ($3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
  WHERE evse_id = $1 AND uid = $2
  RETURNING id, evse_id, uid, identifier, standard, format, power_type, voltage, amperage, wattage, tariff_id, terms_and_conditions, last_updated, publish
`

type UpdateConnectorByEvseParams struct {
	EvseID             int64           `db:"evse_id" json:"evseID"`
	Uid                string          `db:"uid" json:"uid"`
	Identifier         sql.NullString  `db:"identifier" json:"identifier"`
	Standard           ConnectorType   `db:"standard" json:"standard"`
	Format             ConnectorFormat `db:"format" json:"format"`
	PowerType          PowerType       `db:"power_type" json:"powerType"`
	Voltage            int32           `db:"voltage" json:"voltage"`
	Amperage           int32           `db:"amperage" json:"amperage"`
	Wattage            int32           `db:"wattage" json:"wattage"`
	TariffID           sql.NullString  `db:"tariff_id" json:"tariffID"`
	TermsAndConditions sql.NullString  `db:"terms_and_conditions" json:"termsAndConditions"`
	Publish            bool            `db:"publish" json:"publish"`
	LastUpdated        time.Time       `db:"last_updated" json:"lastUpdated"`
}

func (q *Queries) UpdateConnectorByEvse(ctx context.Context, arg UpdateConnectorByEvseParams) (Connector, error) {
	row := q.db.QueryRowContext(ctx, updateConnectorByEvse,
		arg.EvseID,
		arg.Uid,
		arg.Identifier,
		arg.Standard,
		arg.Format,
		arg.PowerType,
		arg.Voltage,
		arg.Amperage,
		arg.Wattage,
		arg.TariffID,
		arg.TermsAndConditions,
		arg.Publish,
		arg.LastUpdated,
	)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.EvseID,
		&i.Uid,
		&i.Identifier,
		&i.Standard,
		&i.Format,
		&i.PowerType,
		&i.Voltage,
		&i.Amperage,
		&i.Wattage,
		&i.TariffID,
		&i.TermsAndConditions,
		&i.LastUpdated,
		&i.Publish,
	)
	return i, err
}
