// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: parking_restriction.sql

package db

import (
	"context"
)

const listParkingRestrictions = `-- name: ListParkingRestrictions :many
SELECT id, text, description FROM parking_restrictions
  ORDER BY id
`

func (q *Queries) ListParkingRestrictions(ctx context.Context) ([]ParkingRestriction, error) {
	rows, err := q.db.QueryContext(ctx, listParkingRestrictions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ParkingRestriction
	for rows.Next() {
		var i ParkingRestriction
		if err := rows.Scan(&i.ID, &i.Text, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
