// Code generated by sqlc. DO NOT EDIT.
// source: pending_notification.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createPendingNotification = `-- name: CreatePendingNotification :one
INSERT INTO pending_notifications (
    user_id,
    node_id,
    invoice_request_id,
    type,
    send_date
  ) VALUES ($1, $2, $3, $4, $5)
  RETURNING id, user_id, node_id, invoice_request_id, type, send_date
`

type CreatePendingNotificationParams struct {
	UserID           int64         `db:"user_id" json:"userID"`
	NodeID           int64         `db:"node_id" json:"nodeID"`
	InvoiceRequestID sql.NullInt64 `db:"invoice_request_id" json:"invoiceRequestID"`
	Type             string        `db:"type" json:"type"`
	SendDate         time.Time     `db:"send_date" json:"sendDate"`
}

func (q *Queries) CreatePendingNotification(ctx context.Context, arg CreatePendingNotificationParams) (PendingNotification, error) {
	row := q.db.QueryRowContext(ctx, createPendingNotification,
		arg.UserID,
		arg.NodeID,
		arg.InvoiceRequestID,
		arg.Type,
		arg.SendDate,
	)
	var i PendingNotification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NodeID,
		&i.InvoiceRequestID,
		&i.Type,
		&i.SendDate,
	)
	return i, err
}

const deletePendingNotification = `-- name: DeletePendingNotification :exec
DELETE FROM pending_notifications
  WHERE id = $1
`

func (q *Queries) DeletePendingNotification(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePendingNotification, id)
	return err
}

const deletePendingNotificationByInvoiceRequest = `-- name: DeletePendingNotificationByInvoiceRequest :exec
DELETE FROM pending_notifications
  WHERE invoice_request_id = $1
  RETURNING id, user_id, node_id, invoice_request_id, type, send_date
`

func (q *Queries) DeletePendingNotificationByInvoiceRequest(ctx context.Context, invoiceRequestID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deletePendingNotificationByInvoiceRequest, invoiceRequestID)
	return err
}

const listPendingNotifications = `-- name: ListPendingNotifications :many
SELECT id, user_id, node_id, invoice_request_id, type, send_date FROM pending_notifications
  WHERE node_id = $1 AND send_date < NOW()
  ORDER BY id
`

func (q *Queries) ListPendingNotifications(ctx context.Context, nodeID int64) ([]PendingNotification, error) {
	rows, err := q.db.QueryContext(ctx, listPendingNotifications, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingNotification
	for rows.Next() {
		var i PendingNotification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NodeID,
			&i.InvoiceRequestID,
			&i.Type,
			&i.SendDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
