// Code generated by sqlc. DO NOT EDIT.
// source: psbt_funding_state.sql

package db

import (
	"context"
	"time"
)

const createPsbtFundingState = `-- name: CreatePsbtFundingState :one
INSERT INTO psbt_funding_states (
    base_psbt,
    psbt, 
    expiry_date
  ) VALUES ($1, $2, $3)
  RETURNING id, base_psbt, psbt, funded_psbt, expiry_date
`

type CreatePsbtFundingStateParams struct {
	BasePsbt   []byte    `db:"base_psbt" json:"basePsbt"`
	Psbt       []byte    `db:"psbt" json:"psbt"`
	ExpiryDate time.Time `db:"expiry_date" json:"expiryDate"`
}

func (q *Queries) CreatePsbtFundingState(ctx context.Context, arg CreatePsbtFundingStateParams) (PsbtFundingState, error) {
	row := q.db.QueryRowContext(ctx, createPsbtFundingState, arg.BasePsbt, arg.Psbt, arg.ExpiryDate)
	var i PsbtFundingState
	err := row.Scan(
		&i.ID,
		&i.BasePsbt,
		&i.Psbt,
		&i.FundedPsbt,
		&i.ExpiryDate,
	)
	return i, err
}

const listPsbtFundingStates = `-- name: ListPsbtFundingStates :many
SELECT id, base_psbt, psbt, funded_psbt, expiry_date FROM psbt_funding_states
  WHERE funded_psbt is null
  ORDER BY id
`

func (q *Queries) ListPsbtFundingStates(ctx context.Context) ([]PsbtFundingState, error) {
	rows, err := q.db.QueryContext(ctx, listPsbtFundingStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PsbtFundingState
	for rows.Next() {
		var i PsbtFundingState
		if err := rows.Scan(
			&i.ID,
			&i.BasePsbt,
			&i.Psbt,
			&i.FundedPsbt,
			&i.ExpiryDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePsbtFundingState = `-- name: UpdatePsbtFundingState :one
UPDATE psbt_funding_states SET (
    psbt,
    funded_psbt
  ) = ($2, $3)
  WHERE id = $1
  RETURNING id, base_psbt, psbt, funded_psbt, expiry_date
`

type UpdatePsbtFundingStateParams struct {
	ID         int64  `db:"id" json:"id"`
	Psbt       []byte `db:"psbt" json:"psbt"`
	FundedPsbt []byte `db:"funded_psbt" json:"fundedPsbt"`
}

func (q *Queries) UpdatePsbtFundingState(ctx context.Context, arg UpdatePsbtFundingStateParams) (PsbtFundingState, error) {
	row := q.db.QueryRowContext(ctx, updatePsbtFundingState, arg.ID, arg.Psbt, arg.FundedPsbt)
	var i PsbtFundingState
	err := row.Scan(
		&i.ID,
		&i.BasePsbt,
		&i.Psbt,
		&i.FundedPsbt,
		&i.ExpiryDate,
	)
	return i, err
}
