// Code generated by sqlc. DO NOT EDIT.
// source: session_invoice.sql

package db

import (
	"context"
	"time"
)

const createSessionInvoice = `-- name: CreateSessionInvoice :one
INSERT INTO session_invoices (
    session_id,
    user_id,
    currency,
    currency_rate,
    currency_rate_msat,
    amount_fiat,
    amount_msat,
    commission_fiat,
    commission_msat,
    tax_fiat,
    tax_msat,
    payment_request,
    is_settled,
    is_expired,
    last_updated
  ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
  RETURNING id, session_id, user_id, currency, currency_rate, currency_rate_msat, amount_fiat, amount_msat, commission_fiat, commission_msat, tax_fiat, tax_msat, payment_request, is_settled, is_expired, last_updated
`

type CreateSessionInvoiceParams struct {
	SessionID        int64     `db:"session_id" json:"sessionID"`
	UserID           int64     `db:"user_id" json:"userID"`
	Currency         string    `db:"currency" json:"currency"`
	CurrencyRate     int64     `db:"currency_rate" json:"currencyRate"`
	CurrencyRateMsat int64     `db:"currency_rate_msat" json:"currencyRateMsat"`
	AmountFiat       float64   `db:"amount_fiat" json:"amountFiat"`
	AmountMsat       int64     `db:"amount_msat" json:"amountMsat"`
	CommissionFiat   float64   `db:"commission_fiat" json:"commissionFiat"`
	CommissionMsat   int64     `db:"commission_msat" json:"commissionMsat"`
	TaxFiat          float64   `db:"tax_fiat" json:"taxFiat"`
	TaxMsat          int64     `db:"tax_msat" json:"taxMsat"`
	PaymentRequest   string    `db:"payment_request" json:"paymentRequest"`
	IsSettled        bool      `db:"is_settled" json:"isSettled"`
	IsExpired        bool      `db:"is_expired" json:"isExpired"`
	LastUpdated      time.Time `db:"last_updated" json:"lastUpdated"`
}

func (q *Queries) CreateSessionInvoice(ctx context.Context, arg CreateSessionInvoiceParams) (SessionInvoice, error) {
	row := q.db.QueryRowContext(ctx, createSessionInvoice,
		arg.SessionID,
		arg.UserID,
		arg.Currency,
		arg.CurrencyRate,
		arg.CurrencyRateMsat,
		arg.AmountFiat,
		arg.AmountMsat,
		arg.CommissionFiat,
		arg.CommissionMsat,
		arg.TaxFiat,
		arg.TaxMsat,
		arg.PaymentRequest,
		arg.IsSettled,
		arg.IsExpired,
		arg.LastUpdated,
	)
	var i SessionInvoice
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Currency,
		&i.CurrencyRate,
		&i.CurrencyRateMsat,
		&i.AmountFiat,
		&i.AmountMsat,
		&i.CommissionFiat,
		&i.CommissionMsat,
		&i.TaxFiat,
		&i.TaxMsat,
		&i.PaymentRequest,
		&i.IsSettled,
		&i.IsExpired,
		&i.LastUpdated,
	)
	return i, err
}

const getSessionInvoice = `-- name: GetSessionInvoice :one
SELECT id, session_id, user_id, currency, currency_rate, currency_rate_msat, amount_fiat, amount_msat, commission_fiat, commission_msat, tax_fiat, tax_msat, payment_request, is_settled, is_expired, last_updated FROM session_invoices
  WHERE id = $1
`

func (q *Queries) GetSessionInvoice(ctx context.Context, id int64) (SessionInvoice, error) {
	row := q.db.QueryRowContext(ctx, getSessionInvoice, id)
	var i SessionInvoice
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Currency,
		&i.CurrencyRate,
		&i.CurrencyRateMsat,
		&i.AmountFiat,
		&i.AmountMsat,
		&i.CommissionFiat,
		&i.CommissionMsat,
		&i.TaxFiat,
		&i.TaxMsat,
		&i.PaymentRequest,
		&i.IsSettled,
		&i.IsExpired,
		&i.LastUpdated,
	)
	return i, err
}

const getSessionInvoiceByPaymentRequest = `-- name: GetSessionInvoiceByPaymentRequest :one
SELECT id, session_id, user_id, currency, currency_rate, currency_rate_msat, amount_fiat, amount_msat, commission_fiat, commission_msat, tax_fiat, tax_msat, payment_request, is_settled, is_expired, last_updated FROM session_invoices
  WHERE payment_request = $1
`

func (q *Queries) GetSessionInvoiceByPaymentRequest(ctx context.Context, paymentRequest string) (SessionInvoice, error) {
	row := q.db.QueryRowContext(ctx, getSessionInvoiceByPaymentRequest, paymentRequest)
	var i SessionInvoice
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Currency,
		&i.CurrencyRate,
		&i.CurrencyRateMsat,
		&i.AmountFiat,
		&i.AmountMsat,
		&i.CommissionFiat,
		&i.CommissionMsat,
		&i.TaxFiat,
		&i.TaxMsat,
		&i.PaymentRequest,
		&i.IsSettled,
		&i.IsExpired,
		&i.LastUpdated,
	)
	return i, err
}

const listSessionInvoices = `-- name: ListSessionInvoices :many
SELECT id, session_id, user_id, currency, currency_rate, currency_rate_msat, amount_fiat, amount_msat, commission_fiat, commission_msat, tax_fiat, tax_msat, payment_request, is_settled, is_expired, last_updated FROM session_invoices
  WHERE session_id = $1
  ORDER BY id
`

func (q *Queries) ListSessionInvoices(ctx context.Context, sessionID int64) ([]SessionInvoice, error) {
	rows, err := q.db.QueryContext(ctx, listSessionInvoices, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionInvoice
	for rows.Next() {
		var i SessionInvoice
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserID,
			&i.Currency,
			&i.CurrencyRate,
			&i.CurrencyRateMsat,
			&i.AmountFiat,
			&i.AmountMsat,
			&i.CommissionFiat,
			&i.CommissionMsat,
			&i.TaxFiat,
			&i.TaxMsat,
			&i.PaymentRequest,
			&i.IsSettled,
			&i.IsExpired,
			&i.LastUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnsettledSessionInvoicesByUserID = `-- name: ListUnsettledSessionInvoicesByUserID :many
SELECT si.id, si.session_id, si.user_id, si.currency, si.currency_rate, si.currency_rate_msat, si.amount_fiat, si.amount_msat, si.commission_fiat, si.commission_msat, si.tax_fiat, si.tax_msat, si.payment_request, si.is_settled, si.is_expired, si.last_updated FROM session_invoices si
  INNER JOIN sessions s ON s.id = si.session_id
  INNER JOIN users u ON u.id = s.user_id
  WHERE u.id = $1 AND si.is_settled != true
  ORDER BY si.id
`

func (q *Queries) ListUnsettledSessionInvoicesByUserID(ctx context.Context, id int64) ([]SessionInvoice, error) {
	rows, err := q.db.QueryContext(ctx, listUnsettledSessionInvoicesByUserID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionInvoice
	for rows.Next() {
		var i SessionInvoice
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserID,
			&i.Currency,
			&i.CurrencyRate,
			&i.CurrencyRateMsat,
			&i.AmountFiat,
			&i.AmountMsat,
			&i.CommissionFiat,
			&i.CommissionMsat,
			&i.TaxFiat,
			&i.TaxMsat,
			&i.PaymentRequest,
			&i.IsSettled,
			&i.IsExpired,
			&i.LastUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionInvoice = `-- name: UpdateSessionInvoice :one
UPDATE session_invoices SET (
    is_settled,
    is_expired,
    last_updated
  ) = ($2, $3, $4)
  WHERE id = $1
  RETURNING id, session_id, user_id, currency, currency_rate, currency_rate_msat, amount_fiat, amount_msat, commission_fiat, commission_msat, tax_fiat, tax_msat, payment_request, is_settled, is_expired, last_updated
`

type UpdateSessionInvoiceParams struct {
	ID          int64     `db:"id" json:"id"`
	IsSettled   bool      `db:"is_settled" json:"isSettled"`
	IsExpired   bool      `db:"is_expired" json:"isExpired"`
	LastUpdated time.Time `db:"last_updated" json:"lastUpdated"`
}

func (q *Queries) UpdateSessionInvoice(ctx context.Context, arg UpdateSessionInvoiceParams) (SessionInvoice, error) {
	row := q.db.QueryRowContext(ctx, updateSessionInvoice,
		arg.ID,
		arg.IsSettled,
		arg.IsExpired,
		arg.LastUpdated,
	)
	var i SessionInvoice
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Currency,
		&i.CurrencyRate,
		&i.CurrencyRateMsat,
		&i.AmountFiat,
		&i.AmountMsat,
		&i.CommissionFiat,
		&i.CommissionMsat,
		&i.TaxFiat,
		&i.TaxMsat,
		&i.PaymentRequest,
		&i.IsSettled,
		&i.IsExpired,
		&i.LastUpdated,
	)
	return i, err
}
