// Code generated by sqlc. DO NOT EDIT.
// source: session_update.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createSessionUpdate = `-- name: CreateSessionUpdate :one
INSERT INTO session_updates (
    session_id,
    user_id,
    kwh,
    total_cost,
    status,
    last_updated
  ) VALUES ($1, $2, $3, $4, $5, $6)
  RETURNING id, session_id, user_id, kwh, total_cost, status, last_updated
`

type CreateSessionUpdateParams struct {
	SessionID   int64             `db:"session_id" json:"sessionID"`
	UserID      int64             `db:"user_id" json:"userID"`
	Kwh         float64           `db:"kwh" json:"kwh"`
	TotalCost   sql.NullFloat64   `db:"total_cost" json:"totalCost"`
	Status      SessionStatusType `db:"status" json:"status"`
	LastUpdated time.Time         `db:"last_updated" json:"lastUpdated"`
}

func (q *Queries) CreateSessionUpdate(ctx context.Context, arg CreateSessionUpdateParams) (SessionUpdate, error) {
	row := q.db.QueryRowContext(ctx, createSessionUpdate,
		arg.SessionID,
		arg.UserID,
		arg.Kwh,
		arg.TotalCost,
		arg.Status,
		arg.LastUpdated,
	)
	var i SessionUpdate
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Kwh,
		&i.TotalCost,
		&i.Status,
		&i.LastUpdated,
	)
	return i, err
}

const listSessionUpdates = `-- name: ListSessionUpdates :many
SELECT id, session_id, user_id, currency, currency_rate, currency_rate_msat, price_fiat, price_msat, commission_fiat, commission_msat, tax_fiat, tax_msat, payment_request, is_settled, is_expired, last_updated, total_fiat, total_msat, estimated_energy, estimated_time, metered_energy, metered_time, signature FROM session_invoices
  WHERE session_id = $1
  ORDER BY id
`

func (q *Queries) ListSessionUpdates(ctx context.Context, sessionID int64) ([]SessionInvoice, error) {
	rows, err := q.db.QueryContext(ctx, listSessionUpdates, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionInvoice
	for rows.Next() {
		var i SessionInvoice
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserID,
			&i.Currency,
			&i.CurrencyRate,
			&i.CurrencyRateMsat,
			&i.PriceFiat,
			&i.PriceMsat,
			&i.CommissionFiat,
			&i.CommissionMsat,
			&i.TaxFiat,
			&i.TaxMsat,
			&i.PaymentRequest,
			&i.IsSettled,
			&i.IsExpired,
			&i.LastUpdated,
			&i.TotalFiat,
			&i.TotalMsat,
			&i.EstimatedEnergy,
			&i.EstimatedTime,
			&i.MeteredEnergy,
			&i.MeteredTime,
			&i.Signature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
