-- Currencies
CREATE TABLE IF NOT EXISTS currencies (
    id           BIGSERIAL PRIMARY KEY,
    name         TEXT NOT NULL,
    code         TEXT NOT NULL,
    numeric_code INT NOT NULL,
    decimals     INT NOT NULL,
    symbol       TEXT
);

CREATE INDEX idx_currencies_code ON currencies (code);

ALTER TABLE currencies 
    ADD CONSTRAINT uq_currencies_code UNIQUE (code);

INSERT INTO currencies (code, numeric_code, decimals, name, symbol) VALUES 
    ('AED', 784, 2, 'UAE Dirham', NULL),
    ('AFN', 971, 2, 'Afghani', '؋'),
    ('ALL', 8, 2, 'Lek', 'Lek'),
    ('AMD', 51, 2, 'Armenian Dram', NULL),
    ('ANG', 532, 2, 'Netherlands Antillean Guilder', 'ƒ'),
    ('AOA', 973, 2, 'Kwanza', NULL),
    ('ARS', 32, 2, 'Argentine Peso', '$'),
    ('AUD', 36, 2, 'Australian Dollar', '$'),
    ('AWG', 533, 2, 'Aruban Florin', NULL),
    ('AZN', 944, 2, 'Azerbaijani Manat', 'ман'),
    ('BAM', 977, 2, 'Convertible Mark', 'KM'),
    ('BBD', 52, 2, 'Barbados Dollar', '$'),
    ('BDT', 50, 2, 'Taka', NULL),
    ('BGN', 975, 2, 'Bulgarian Lev', 'лв'),
    ('BHD', 48, 3, 'Bahraini Dinar', NULL),
    ('BIF', 108, 0, 'Burundian Franc', NULL),
    ('BMD', 60, 2, 'Bermudian Dollar', '$'),
    ('BND', 96, 2, 'Brunei Dollar', '$'),
    ('BOB', 68, 2, 'Boliviano', NULL),
    ('BOV', 984, 2, 'Bolivian Mvdol', '$b'),
    ('BRL', 986, 2, 'Brazilian Real', 'R$'),
    ('BSD', 44, 2, 'Bahamian Dollar', '$'),
    ('BTN', 64, 2, 'Bhutanese Ngultrum', NULL),
    ('BWP', 72, 2, 'Pula', 'P'),
    ('BYR', 974, 0, 'Belarusian Ruble', 'p.'),
    ('BZD', 84, 2, 'Belize Dollar', 'BZ$'),
    ('CAD', 124, 2, 'Canadian Dollar', '$'),
    ('CDF', 976, 2, 'Congolese Franc', NULL),
    ('CHE', 947, 2, 'WIR Euro', NULL),
    ('CHF', 756, 2, 'Swiss Franc', 'CHF'),
    ('CHW', 948, 2, 'WIR Franc', NULL),
    ('CLF', 990, 0, 'Unidad De Fomento', NULL),
    ('CLP', 152, 0, 'Chilean Peso', '$'),
    ('CNY', 156, 2, 'Chinese Yuan', '¥'),
    ('COP', 170, 2, 'Colombian Peso', '$'),
    ('COU', 970, 2, 'Unidad De Valor Real', NULL),
    ('CRC', 188, 2, 'Costa Rican Colon', '₡'),
    ('CUC', 931, 2, 'Cuban Convertible Peso', '₱'),
    ('CUP', 192, 2, 'Cuban Peso', '₱'),
    ('CVE', 132, 0, 'Cape Verde Escudo', NULL),
    ('CZK', 203, 2, 'Czech Koruna', 'Kč'),
    ('DJF', 262, 0, 'Djiboutian Franc', NULL),
    ('DKK', 208, 2, 'Danish Krone', 'kr'),
    ('DOP', 214, 2, 'Dominican Peso', 'RD$'),
    ('DZD', 12, 2, 'Algerian Dinar', NULL),
    ('EGP', 818, 2, 'Egyptian Pound', '£'),
    ('ERN', 232, 2, 'Nakfa', NULL),
    ('ETB', 230, 2, 'Ethiopian Birr', NULL),
    ('EUR', 978, 2, 'Euro', '€'),
    ('FJD', 242, 2, 'Fiji Dollar', '$'),
    ('FKP', 238, 2, 'Falkland Islands Pound', '£'),
    ('GBP', 826, 2, 'Pound Sterling', '£'),
    ('GEL', 981, 2, 'Lari', NULL),
    ('GHS', 936, 2, 'Cedi', NULL),
    ('GIP', 292, 2, 'Gibraltar Pound', '£'),
    ('GMD', 270, 2, 'Dalasi', NULL),
    ('GNF', 324, 0, 'Guinean Franc', NULL),
    ('GTQ', 320, 2, 'Quetzal', 'Q'),
    ('GYD', 328, 2, 'Guyanese Dollar', '$'),
    ('HKD', 344, 2, 'Hong Kong Dollar', '$'),
    ('HNL', 340, 2, 'Lempira', 'L'),
    ('HRK', 191, 2, 'Croatian Kuna', 'kn'),
    ('HTG', 332, 2, 'Haitian Gourde', NULL),
    ('HUF', 348, 2, 'Forint', 'Ft'),
    ('IDR', 360, 2, 'Rupiah', 'Rp'),
    ('ILS', 376, 2, 'Israeli New Shekel', '₪'),
    ('INR', 356, 2, 'Indian Rupee', NULL),
    ('IQD', 368, 3, 'Iraqi Dinar', NULL),
    ('IRR', 364, 0, 'Iranian Rial', '﷼'),
    ('ISK', 352, 0, 'Icelandic Króna', 'kr'),
    ('JMD', 388, 2, 'Jamaican Dollar', 'J$'),
    ('JOD', 400, 3, 'Jordanian Dinar', NULL),
    ('JPY', 392, 0, 'Yen', '¥'),
    ('KES', 404, 2, 'Kenyan Shilling', NULL),
    ('KGS', 417, 2, 'Som', 'лв'),
    ('KHR', 116, 2, 'Riel', '៛'),
    ('KMF', 174, 0, 'Comoro Franc', NULL),
    ('KPW', 408, 0, 'North Korean Won', '₩'),
    ('KRW', 410, 0, 'Won', '₩'),
    ('KWD', 414, 3, 'Kuwaiti Dinar', NULL),
    ('KYD', 136, 2, 'Cayman Islands Dollar', '$'),
    ('KZT', 398, 2, 'Tenge', 'лв'),
    ('LAK', 418, 0, 'Kip', '₭'),
    ('LBP', 422, 0, 'Lebanese Pound', '£'),
    ('LKR', 144, 2, 'Sri Lankan Rupee', '₨'),
    ('LRD', 430, 2, 'Liberian Dollar', '$'),
    ('LSL', 426, 2, 'Lesotho Loti', NULL),
    ('LTL', 440, 2, 'Lithuanian Litas', 'Lt'),
    ('LVL', 428, 2, 'Latvian Lats', 'Ls'),
    ('LYD', 434, 3, 'Libyan Dinar', NULL),
    ('MAD', 504, 2, 'Moroccan Dirham', NULL),
    ('MDL', 498, 2, 'Moldovan Leu', NULL),
    ('MGA', 969, 2, 'Malagasy Ariary', NULL),
    ('MKD', 807, 0, 'Denar', 'ден'),
    ('MMK', 104, 0, 'Kyat', NULL),
    ('MNT', 496, 2, 'Tugrik', '₮'),
    ('MOP', 446, 2, 'Pataca', NULL),
    ('MRO', 478, 2, 'Ouguiya', NULL),
    ('MUR', 480, 2, 'Mauritian Rupee', '₨'),
    ('MVR', 462, 2, 'Rufiyaa', NULL),
    ('MWK', 454, 2, 'Kwacha', NULL),
    ('MXN', 484, 2, 'Mexican Peso', '$'),
    ('MXV', 979, 2, 'Mexican UDI', '$'),
    ('MYR', 458, 2, 'Malaysian Ringgit', 'RM'),
    ('MZN', 943, 2, 'Metical', 'MT'),
    ('NAD', 516, 2, 'Namibian Dollar', NULL),
    ('NGN', 566, 2, 'Naira', '₦'),
    ('NIO', 558, 2, 'Córdoba Oro', 'C$'),
    ('NOK', 578, 2, 'Norwegian Krone', 'kr'),
    ('NPR', 524, 2, 'Nepalese Rupee', '₨'),
    ('NZD', 554, 2, 'New Zealand Dollar', '$'),
    ('OMR', 512, 3, 'Omani Rial', '﷼'),
    ('PAB', 590, 2, 'Panamanian Balboa', 'B/.'),
    ('PEN', 604, 2, 'Nuevo Sol', 'S/.'),
    ('PGK', 598, 2, 'Kina', NULL),
    ('PHP', 608, 2, 'Philippine Peso', 'Php'),
    ('PKR', 586, 2, 'Pakistani Rupee', '₨'),
    ('PLN', 985, 2, 'Złoty', 'zł'),
    ('PYG', 600, 0, 'Guaraní', 'Gs'),
    ('QAR', 634, 2, 'Qatari Riyal', '﷼'),
    ('RON', 946, 2, 'New Leu', 'lei'),
    ('RSD', 941, 2, 'Serbian Dinar', 'Дин.'),
    ('RUB', 643, 2, 'Russian Rouble', 'руб'),
    ('RWF', 646, 0, 'Rwandan Franc', NULL),
    ('SAR', 682, 2, 'Saudi Riyal', '﷼'),
    ('SBD', 90, 2, 'Solomon Islands Dollar', '$'),
    ('SCR', 690, 2, 'Seychelles Rupee', '₨'),
    ('SDG', 938, 2, 'Sudanese Pound', NULL),
    ('SEK', 752, 2, 'Swedish Krona', 'kr'),
    ('SGD', 702, 2, 'Singapore Dollar', '$'),
    ('SHP', 654, 2, 'Saint Helena Pound', '£'),
    ('SLL', 694, 0, 'Leone', NULL),
    ('SOS', 706, 2, 'Somali Shilling', 'S'),
    ('SRD', 968, 2, 'Surinamese Dollar', '$'),
    ('SSP', 728, 2, 'South Sudanese Pound', '£'),
    ('STD', 678, 0, 'Dobra', NULL),
    ('SYP', 760, 2, 'Syrian Pound', '£'),
    ('SZL', 748, 2, 'Lilangeni', NULL),
    ('THB', 764, 2, 'Baht', '฿'),
    ('TJS', 972, 2, 'Somoni', NULL),
    ('TMT', 934, 2, 'Manat', NULL),
    ('TND', 788, 3, 'Tunisian Dinar', NULL),
    ('TOP', 776, 2, 'Paʻanga', NULL),
    ('TRY', 949, 2, 'Turkish Lira', 'TL'),
    ('TTD', 780, 2, 'Trinidad And Tobago Dollar', 'TT$'),
    ('TWD', 901, 2, 'New Taiwan Dollar', 'NT$'),
    ('TZS', 834, 2, 'Tanzanian Shilling', NULL),
    ('UAH', 980, 2, 'Hryvnia', '₴'),
    ('UGX', 800, 2, 'Ugandan Shilling', NULL),
    ('USD', 840, 2, 'United States Dollar', '$'),
    ('UYI', 940, 0, 'Uruguay Peso En Unidades Indexadas', '$U'),
    ('UYU', 858, 2, 'Uruguayan Peso', '$U'),
    ('UZS', 860, 2, 'Uzbekistan Som', 'лв'),
    ('VEF', 937, 2, 'Bolívar Fuerte', 'Bs'),
    ('VND', 704, 0, 'Dong', '₫'),
    ('VUV', 548, 0, 'Vatu', NULL),
    ('WST', 882, 2, 'Tala', NULL),
    ('XAF', 950, 0, 'CFA Franc BEAC', NULL),
    ('XCD', 951, 2, 'East Caribbean Dollar', '$'),
    ('XOF', 952, 0, 'CFA Franc BCEAO', NULL),
    ('XPF', 953, 0, 'CFP Franc', NULL),
    ('YER', 886, 2, 'Yemeni Rial', '﷼'),
    ('ZAR', 710, 2, 'Rand', 'R'),
    ('ZMW', 967, 2, 'Zambian Kwacha', NULL);
