// Code generated by sqlc. DO NOT EDIT.
// source: tariff.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createTariff = `-- name: CreateTariff :one
INSERT INTO Tariffs (
    uid, 
    currency, 
    tariff_alt_url, 
    energy_mix_id, 
    last_updated
  ) VALUES ($1, $2, $3, $4, $5)
  RETURNING id, uid, currency, tariff_alt_url, energy_mix_id, last_updated
`

type CreateTariffParams struct {
	Uid          string         `db:"uid" json:"uid"`
	Currency     string         `db:"currency" json:"currency"`
	TariffAltUrl sql.NullString `db:"tariff_alt_url" json:"tariffAltUrl"`
	EnergyMixID  sql.NullInt64  `db:"energy_mix_id" json:"energyMixID"`
	LastUpdated  time.Time      `db:"last_updated" json:"lastUpdated"`
}

func (q *Queries) CreateTariff(ctx context.Context, arg CreateTariffParams) (Tariff, error) {
	row := q.db.QueryRowContext(ctx, createTariff,
		arg.Uid,
		arg.Currency,
		arg.TariffAltUrl,
		arg.EnergyMixID,
		arg.LastUpdated,
	)
	var i Tariff
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Currency,
		&i.TariffAltUrl,
		&i.EnergyMixID,
		&i.LastUpdated,
	)
	return i, err
}

const deleteTariffByUid = `-- name: DeleteTariffByUid :one
DELETE FROM Tariffs
  WHERE uid = $1
  RETURNING id, uid, currency, tariff_alt_url, energy_mix_id, last_updated
`

func (q *Queries) DeleteTariffByUid(ctx context.Context, uid string) (Tariff, error) {
	row := q.db.QueryRowContext(ctx, deleteTariffByUid, uid)
	var i Tariff
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Currency,
		&i.TariffAltUrl,
		&i.EnergyMixID,
		&i.LastUpdated,
	)
	return i, err
}

const getTariffByUid = `-- name: GetTariffByUid :one
SELECT id, uid, currency, tariff_alt_url, energy_mix_id, last_updated FROM Tariffs
  WHERE uid = $1
`

func (q *Queries) GetTariffByUid(ctx context.Context, uid string) (Tariff, error) {
	row := q.db.QueryRowContext(ctx, getTariffByUid, uid)
	var i Tariff
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Currency,
		&i.TariffAltUrl,
		&i.EnergyMixID,
		&i.LastUpdated,
	)
	return i, err
}

const updateTariffByUid = `-- name: UpdateTariffByUid :one
UPDATE Tariffs SET (
    currency, 
    tariff_alt_url,
    energy_mix_id, 
    last_updated
  ) = ($2, $3, $4, $5)
  WHERE uid = $1
  RETURNING id, uid, currency, tariff_alt_url, energy_mix_id, last_updated
`

type UpdateTariffByUidParams struct {
	Uid          string         `db:"uid" json:"uid"`
	Currency     string         `db:"currency" json:"currency"`
	TariffAltUrl sql.NullString `db:"tariff_alt_url" json:"tariffAltUrl"`
	EnergyMixID  sql.NullInt64  `db:"energy_mix_id" json:"energyMixID"`
	LastUpdated  time.Time      `db:"last_updated" json:"lastUpdated"`
}

func (q *Queries) UpdateTariffByUid(ctx context.Context, arg UpdateTariffByUidParams) (Tariff, error) {
	row := q.db.QueryRowContext(ctx, updateTariffByUid,
		arg.Uid,
		arg.Currency,
		arg.TariffAltUrl,
		arg.EnergyMixID,
		arg.LastUpdated,
	)
	var i Tariff
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Currency,
		&i.TariffAltUrl,
		&i.EnergyMixID,
		&i.LastUpdated,
	)
	return i, err
}
