// Code generated by sqlc. DO NOT EDIT.
// source: token.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (
    uid, 
    type,
    auth_id,
    visual_number,
    issuer,
    valid,
    whitelist,
    language,
    last_updated
  ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
  RETURNING id, uid, type, auth_id, visual_number, issuer, valid, whitelist, language, last_updated
`

type CreateTokenParams struct {
	Uid          string             `db:"uid" json:"uid"`
	Type         TokenType          `db:"type" json:"type"`
	AuthID       string             `db:"auth_id" json:"authID"`
	VisualNumber sql.NullString     `db:"visual_number" json:"visualNumber"`
	Issuer       string             `db:"issuer" json:"issuer"`
	Valid        bool               `db:"valid" json:"valid"`
	Whitelist    TokenWhitelistType `db:"whitelist" json:"whitelist"`
	Language     string             `db:"language" json:"language"`
	LastUpdated  time.Time          `db:"last_updated" json:"lastUpdated"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, createToken,
		arg.Uid,
		arg.Type,
		arg.AuthID,
		arg.VisualNumber,
		arg.Issuer,
		arg.Valid,
		arg.Whitelist,
		arg.Language,
		arg.LastUpdated,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Type,
		&i.AuthID,
		&i.VisualNumber,
		&i.Issuer,
		&i.Valid,
		&i.Whitelist,
		&i.Language,
		&i.LastUpdated,
	)
	return i, err
}

const deleteTokenByUid = `-- name: DeleteTokenByUid :exec
DELETE FROM tokens
  WHERE uid = $1
`

func (q *Queries) DeleteTokenByUid(ctx context.Context, uid string) error {
	_, err := q.db.ExecContext(ctx, deleteTokenByUid, uid)
	return err
}

const getTokenByUid = `-- name: GetTokenByUid :one
SELECT id, uid, type, auth_id, visual_number, issuer, valid, whitelist, language, last_updated FROM tokens
  WHERE uid = $1
`

func (q *Queries) GetTokenByUid(ctx context.Context, uid string) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenByUid, uid)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Type,
		&i.AuthID,
		&i.VisualNumber,
		&i.Issuer,
		&i.Valid,
		&i.Whitelist,
		&i.Language,
		&i.LastUpdated,
	)
	return i, err
}

const updateTokenByUid = `-- name: UpdateTokenByUid :one
UPDATE tokens SET (
    type,
    auth_id,
    visual_number,
    issuer,
    valid,
    whitelist,
    language,
    last_updated
  ) = ($2, $3, $4, $5, $6, $7, $8, $9)
  WHERE uid = $1
  RETURNING id, uid, type, auth_id, visual_number, issuer, valid, whitelist, language, last_updated
`

type UpdateTokenByUidParams struct {
	Uid          string             `db:"uid" json:"uid"`
	Type         TokenType          `db:"type" json:"type"`
	AuthID       string             `db:"auth_id" json:"authID"`
	VisualNumber sql.NullString     `db:"visual_number" json:"visualNumber"`
	Issuer       string             `db:"issuer" json:"issuer"`
	Valid        bool               `db:"valid" json:"valid"`
	Whitelist    TokenWhitelistType `db:"whitelist" json:"whitelist"`
	Language     string             `db:"language" json:"language"`
	LastUpdated  time.Time          `db:"last_updated" json:"lastUpdated"`
}

func (q *Queries) UpdateTokenByUid(ctx context.Context, arg UpdateTokenByUidParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, updateTokenByUid,
		arg.Uid,
		arg.Type,
		arg.AuthID,
		arg.VisualNumber,
		arg.Issuer,
		arg.Valid,
		arg.Whitelist,
		arg.Language,
		arg.LastUpdated,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Type,
		&i.AuthID,
		&i.VisualNumber,
		&i.Issuer,
		&i.Valid,
		&i.Whitelist,
		&i.Language,
		&i.LastUpdated,
	)
	return i, err
}
