// Code generated by sqlc. DO NOT EDIT.
// source: token_authorization_connector.sql

package db

import (
	"context"
)

const listTokenAuthorizationConnectors = `-- name: ListTokenAuthorizationConnectors :many
SELECT e.id, e.evse_id, e.uid, e.standard, e.format, e.power_type, e.voltage, e.amperage, e.tariff_id, e.terms_and_conditions, e.last_updated FROM connectors e
  INNER JOIN token_authorization_connectors tac ON tac.connector_uid = e.uid
  WHERE tac.token_authorization_id = $1
  ORDER BY e.id
`

func (q *Queries) ListTokenAuthorizationConnectors(ctx context.Context, tokenAuthorizationID int64) ([]Connector, error) {
	rows, err := q.db.QueryContext(ctx, listTokenAuthorizationConnectors, tokenAuthorizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Connector
	for rows.Next() {
		var i Connector
		if err := rows.Scan(
			&i.ID,
			&i.EvseID,
			&i.Uid,
			&i.Standard,
			&i.Format,
			&i.PowerType,
			&i.Voltage,
			&i.Amperage,
			&i.TariffID,
			&i.TermsAndConditions,
			&i.LastUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTokenAuthorizationConnector = `-- name: SetTokenAuthorizationConnector :exec
INSERT INTO token_authorization_connectors (token_authorization_id, connector_uid)
  VALUES ($1, $2)
`

type SetTokenAuthorizationConnectorParams struct {
	TokenAuthorizationID int64  `db:"token_authorization_id" json:"tokenAuthorizationID"`
	ConnectorUid         string `db:"connector_uid" json:"connectorUid"`
}

func (q *Queries) SetTokenAuthorizationConnector(ctx context.Context, arg SetTokenAuthorizationConnectorParams) error {
	_, err := q.db.ExecContext(ctx, setTokenAuthorizationConnector, arg.TokenAuthorizationID, arg.ConnectorUid)
	return err
}
