// Code generated by sqlc. DO NOT EDIT.
// source: weekday.sql

package db

import (
	"context"
)

const listWeekdays = `-- name: ListWeekdays :many
SELECT id, text, description FROM weekdays
  ORDER BY id
`

func (q *Queries) ListWeekdays(ctx context.Context) ([]Weekday, error) {
	rows, err := q.db.QueryContext(ctx, listWeekdays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Weekday
	for rows.Next() {
		var i Weekday
		if err := rows.Scan(&i.ID, &i.Text, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
